# Generated by Django 4.0.2 on 2022-03-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aholi', models.CharField(max_length=60)),
                ('soni', models.FloatField()),
                ('malumot', models.TextField(max_length=1000)),
            ],
        ),
    ]
