# Generated by Django 4.0.2 on 2022-03-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_part1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part1',
            name='img',
            field=models.ImageField(upload_to='media'),
        ),
    ]
