# Generated by Django 4.0.2 on 2022-03-03 08:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0003_alter_part1_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SivilNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
