# Generated by Django 4.0.2 on 2022-03-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0004_sivilnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employes_img', models.ImageField(upload_to='media/')),
                ('employes_name', models.CharField(max_length=64)),
                ('employes_info', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Part1',
        ),
    ]
