# Generated by Django 4.0.2 on 2022-03-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0005_employes_delete_part1'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.FileField(upload_to='video/')),
                ('title', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='employes',
            name='employes_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
