# Generated by Django 4.0.2 on 2022-03-04 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0006_newvideo_alter_employes_employes_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employes',
            options={'verbose_name_plural': 'Ishchilar'},
        ),
        migrations.AlterModelOptions(
            name='newvideo',
            options={'verbose_name_plural': 'Video'},
        ),
        migrations.RemoveField(
            model_name='part',
            name='malumot',
        ),
        migrations.RemoveField(
            model_name='part',
            name='soni',
        ),
    ]
