# Generated by Django 4.0.2 on 2022-03-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0008_yangihodim_delete_part_alter_employes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangihodim',
            name='haqida',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='yangihodim',
            name='ismi',
            field=models.CharField(max_length=60),
        ),
    ]
