# Generated by Django 4.0.2 on 2022-03-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0009_alter_yangihodim_haqida_alter_yangihodim_ismi'),
    ]

    operations = [
        migrations.CreateModel(
            name='IbratRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media/media/')),
            ],
        ),
        migrations.AlterField(
            model_name='yangihodim',
            name='rasmi',
            field=models.ImageField(upload_to='media/media/'),
        ),
    ]
