# Generated by Django 4.0.2 on 2022-03-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0011_jamoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='UzgarishYangiliklar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uzgarish', models.TextField(max_length=200)),
            ],
        ),
    ]
