# Generated by Django 4.0.2 on 2022-03-05 08:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0013_komishodim'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxallFuqorolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
